### ISSUE TITLE
Bug: Unsupported URL

### ISSUE THREAD

**Issue by Calorion** [lstrzepek/obsidian-yt-transcript#51]
**Plugin version**
0.9.2

**Describe the bug**
I get "Request failed. unsupported URL" in the sidebar when I use YT-transcript.

**Youtube link**

https://youtu.be/bCX0Py6-po8?si=MK1PPwnOFKXUwT2p

**Expected behavior**
It fetches the transcript.

**Screenshots**
![image](https://github.com/lstrzepek/obsidian-yt-transcript/assets/3050950/79623db5-ef67-49c1-b481-ea8a5b36105a)

**Comment by lstrzepek** [comment]
Hi yes that’s inconvenient but short url won’t work. You have to use full one.


Wiadomość napisana przez Calion ***@***.***> w dniu 08.06.2024, o godz. 15:27:

﻿

Plugin version
0.9.2

Describe the bug
I get "Request failed: Unsupported URL" in the sidebar when I use YT.

Youtube link

https://youtu.be/bCX0Py6-po8?si=MK1PPwnOFKXUwT2p

Expected behavior
It fetches the transcript.

Screenshots
DECE4574-A19B-470F-B09C-10E69B223A97.jpeg (view on web)<https://github.com/lstrzepek/obsidian-yt-transcript/assets/3050950/79623db5-ef67-49c1-b481-ea8a5b36105a>

**Comment by agu3rra** [comment]
Related bug: #50 
Probably closing one also closes the other.

**Comment by agu3rra** [comment]
@lstrzepek 
Are you still accepting PR's on this repository?

**Comment by lstrzepek** [comment]
this is a duplicate of #50 
link is working on desktop version

**Comment by agu3rra** [comment]
Thank you for the #55 fix @lstrzepek ! 🙏
